### ISSUE TITLE
Any difference between PV-LIO and the software code of alpha-lidar

### ISSUE THREAD

**Issue by CharlieV5** [HViktorTsoi/alpha_lidar#12]
Hi!
I have followed you works of PV-LIO and noticed that the software code of alpha-lidar seems to be almost using the same code of PV-LIO. So what is the crucial difference between PV-LIO and alpha-lidar software code ?

**Comment by HViktorTsoi** [comment]
Hi! PV-LIO is an under-developing version of αLiDAR. There are two main updates of this repo compared with PV-LIO  :
1. Non-static initialization for rapid rotation scenarios.
2. Uncoupled motor encoder fusion.
