### ISSUE TITLE
Regarding the source of the topic /imu/encoder

### ISSUE THREAD

**Issue by Luthermorning** [HViktorTsoi/alpha_lidar#13]
Thank you for your open source work for contributing to the community, I would like to know how your encoder data is emitted from STM32 and received in ROS, can you discuss this with you.

**Comment by HViktorTsoi** [comment]
Hi,  the data link path of the encoder message is like this:

Motor --> [Encoder angle packets] --> CAN --> stm32 --> [Timestamping and packing the angle packets together with adjecent IMU packets] --> USART --> Host machine --> ROS serial driver --> [Decode both IMU and angle packets and publish them as `/imu/data` and `/imu/encoder`]

**Comment by Luthermorning** [comment]
> Hi, the data link path of the encoder message is like this:
> 
> Motor --> [Encoder angle packets] --> CAN --> stm32 --> [Timestamping and packing the angle packets together with adjecent IMU packets] --> USART --> Host machine --> ROS serial driver --> [Decode both IMU and angle packets and publish them as `/imu/data` and `/imu/encoder`]

Thanks, it`s cool.
