### ISSUE TITLE
LiDAR-lMU-Motor central mounting structure for Livox Lidars.

### ISSUE THREAD

**Issue by 85256638** [HViktorTsoi/alpha_lidar#14]
Thanks a lot for open-sourcing this great project.

Would be able to provide the CAD design files for other Lidars please? Especially the Livox Horizon and Livox Mid-360. 
The current repository only contains designs for two Lidars:

![image](https://github.com/user-attachments/assets/e4d89b4e-2600-45f2-b069-36abcdb3d3e8)

**Comment by HViktorTsoi** [comment]
#11

**Comment by HViktorTsoi** [comment]
#8
