### ISSUE TITLE
Host Machine & Livox IMU info

### ISSUE THREAD

**Issue by satyajit-ink** [HViktorTsoi/alpha_lidar#6]
what is the details of the host machine used with alpha lidar?

also is the external IMU necessary in case of Livox Lidar's with inbuilt IMU?

**Comment by HViktorTsoi** [comment]
Hi, you could use a normal laptop (with Ethernet and USB interface) as the host machine. For reference, we're using a Lenovo LEGION R7000P laptop with NVIDIA 2060GPU and 16-core CPUs.

For Livox LiDARs, the external IMU is not required, you could use the built-in 6-axis IMU. However, if the test scenario requires dynamic initialization, you may need [imu_filter_madgwick](https://wiki.ros.org/imu_filter_madgwick) to generate the initial imu orientation.
